#
name: cwerg-tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master




jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.7]
        os: [ubuntu-latest]
        #python-version: [3.7, 3.8, 3.9]
        #os: [ubuntu-latest, macos-latest, windows-latest]

    steps:

    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python Deps
      run: |
        python -m pip install --upgrade pip
        pip install pycparser
    - name: Install Ubuntu Deps
      run: |
        sudo apt-get install qemu-user-static libunwind-dev gcc-multilib
    - name: Show Version Summary
      run: |
        uname -a
        echo
        lsb_release -a
        echo
        python -V
        echo
        python3 -V
        echo
        gcc -v
        echo
        g++ -v
        echo
        clang -v
        echo
        clang++ -v
    - name: Run Tests
      run: |
        PYPY=python3 CC=clang CXX=clang++ MAKESILENT= make tests_github
    - name: Integration Tests
      run: |
        PYPY=python3 CC=gcc CXX=g++ MAKESILENT= make integration_tests
